version: "3"
services:
  app:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5001:5001"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - database
    restart: always
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: dans-app
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always
volumes:
  db_data:
